# Config file for automatic testing at travis-ci.org

language: python

addons:
  postgresql: '9.4'

python:
  - "3.4"
  - "2.7"

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: make install

# command to run tests, e.g. python setup.py test
script: make test
