# Config file for automatic testing at travis-ci.org

language: python

addons:
  postgresql: '9.4'

python:
  #- "3.4"
  #- "3.3"
  - "2.7"

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -r requirements-travis.txt

# command to run tests, e.g. python setup.py test
script: make test
